language: rust
sudo: false
cache:
  yarn: true
  cargo: true

matrix:
  include:
  # Builds with wasm-pack.
  - rust: beta
    before_install:
      - nvm install node
      - npm install -g yarn
    before_script:
      - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
    script:
      - yarn
      - yarn build

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

